# applier Makefile

CAPABILITY_ID = "wasmcloud:example:applier"
NAME = "applier"
VENDOR = "cosmonic"
PROJECT = applier
VERSION = 0.1.0
REVISION = 0

include ./provider.mk

test::
	cargo clippy --all-targets --all-features

