name: Build

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: "ubuntu-latest" }
          - { os: "macos-latest" }
          - { os: "windows-latest" }

    steps:
      - uses: actions/checkout@v2
      - name: Install latest Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          components: clippy, rustfmt
      - name: Build
        run: make build

  integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          components: clippy, rustfmt
      - name: Build
        run: make build
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"
      # Because we are using rustls-tls, the credentials for the kubernetes cluster can't be a bare IP
      - name: Use localhost for kubeconfig
        run: |
          sed -i "" 's/127.0.0.1/localhost/g' ~/.kube/config
      - name: Run tests
        run: make test
